### ISSUE TITLE
why is not using dictionary???????

### ISSUE THREAD

**Issue by sertdfyguhi** [SpeckyYT/LXR#1]
i am confuse

**Comment by SpeckyYT** [comment]
for what

**Comment by sertdfyguhi** [comment]
```
@lxr::new({
    "+": "PLUS",
    "-": "MINUS",
    ">": "FORWARD",
    "<": "BACKWARD",
    ".": "DOT",
    ",": "COMMA",
    "[": "OPEN",
    "]": "CLOSE",
    regex("."), "ignore",
})
```
 i feel like im stupid or smth please explain

**Comment by SpeckyYT** [comment]
> ```
> @lxr::new({
>     "+": "PLUS",
>     "-": "MINUS",
>     ">": "FORWARD",
>     "<": "BACKWARD",
>     ".": "DOT",
>     ",": "COMMA",
>     "[": "OPEN",
>     "]": "CLOSE",
>     regex("."), "ignore",
> })
> ```
> 
> i feel like im stupid or smth please explain

regex aren't valid values to index dicts with, therefore the best way is to have it as an array

also using dict.entries() is uglier than having it as an array (plus, the sequence should be preserved)

**Comment by sertdfyguhi** [comment]
damn spwn stupid
